### PR TITLE
Update colors with new base16-project/base16-scheme repo

### PR DESCRIPTION
**Pull request by JamyGolden**
Hi @mattdavis90, there is a group of us working on reviving the base16 project and I'm wondering if you'd be willing to join.

The discussion about a base16 Github organization initially started in 2016: https://github.com/chriskempson/base16/issues/74. With the disappearance of Chris Kempson the importance of the [base16](https://github.com/chriskempson/base16) organization is more vital than ever to keep the project structured and thriving. Currently there is a deprecated notice on the old base16 repo.

Seeing as you've created this repo, we're [looking for more colaborators](https://github.com/base16-project/base16/issues/2) and I was wondering if you are you interested in joining [github.com/base16-project](https://github.com/base16-project) and helping us maintain some of the projects?

Right now, communication around this is happening at https://github.com/base16-project/base16/issues/1 (Some of us are also on #base16 on Libera Chat [IRC] for more general discussions and hangouts)

Are you interested in maintaining any [base16-project](https://github.com/base16-project) repositories and being part of the organization?

### CODE REVIEW

**Comment by mattdavis90** [comment]
Hi,

Firstly thanks for the update of colour schemes. I'd be very interested in joining the project and would be happy to have this repo be part of it. I personally use 3 base16 repos so have a vested interest in keeping them up to date.

kitty (https://github.com/kdrag0n/base16-kitty)
tmux (https://github.com/mattdavis90/base16-tmux)
nvim (https://github.com/RRethy/nvim-base16)

Happy to help in any way I can. Thanks

**Comment by JamyGolden** [comment]
@mattdavis90 great to have you on board! I've added you to the org so you should be able to transfer the repo. I've sent a message to the maintainer of the base16-kitty repo too. I'm a bit conflicted with the concept of a neovim base16 repo (I use neovim myself), I feel like it could somehow exist within the base16-vim repo. I haven't thought too much about it but those are my initial feelings. I'm happy to discuss it with the others and see what the best way to go forward with those 2 repos are :smile:

I'll add you as a maintainer of base16-kitty if/when they decide to join base16-project, and if you want to be involved in any other base16-project repos that you aren't a maintainer of, feel free to send me a message at any point and I'll add you!

**Comment by JamyGolden** [comment]
Out of interest, any reason you use base16-kitty and not base16-shell?

**Comment by mattdavis90** [comment]
No particular reason. I used the gnome-terminal one before switching to kitty and by default searched for "base16-kitty" but having now had a play around with the "base16-shell" repo I'm not entirely sure what I gain - if anything - from using a terminal emulator specific config. The colours looks the same either way and I haven't found anything that isn't working so will probably stick with "base16-shell" for now. Thanks for the tip, no idea how I haven't used it before

**Comment by mattdavis90** [comment]
In response to the nvim vs. vim comment. I use the base16-nvim repo because it is lua based and has support for Telescope and the notify API

**Comment by JamyGolden** [comment]
👍 I'll build in support for that and look at maybe having a lua template included in the repo for people who only want to use lua.

**Pull request merged**
